---
bot_name:
  'Blitz Statistics'

session_ttl: 86400

default: 
  prefix : '!'
  lang: 'en'
  available_locales: ['ru', 'en', 'pl', 'ua', 'auto']
  locale_alliases: {ru: 'ru', en: 'en', pl: 'pl', uk: 'ua'}
  available_regions: ['ru', 'eu', 'na', 'asia']