---

# This YAML file use placeholders:
# format: <key_name>
#
# Example:
#   srv_id: "server_id: <id>"
#
# _Zener
bot_name:
  'Blitz Statistics'

server:
  host: '127.0.0.1'
  port: 8000

session:
  ttl: 172_800 # in seconds

autosession:
  ttl: 2_592_000 # in seconds

default:
  prefix : '!'  # deprecated
  lang: 'en'
  available_locales: ['ru', 'en', 'pl', 'ua', 'auto']
  available_regions: ['ru', 'eu', 'na', 'asia']
  locale_aliases: {ru: 'ru', en: 'en', pl: 'pl', uk: 'ua'}

image:
  default_bg_path: 'res/image/default_image/default_bg.png'

internal:
  ignore_tankopedia_failures: true

help_urls:
  ru: https://blitzhub.gitbook.io/blitz-statistics-bot/ru-docs
  en: https://blitzhub.gitbook.io/blitz-statistics-bot/en-docs
  ua: https://blitzhub.gitbook.io/blitz-statistics-bot/ua-docs
  pl: https://blitzhub.gitbook.io/blitz-statistics-bot/pl-docs

auth:
  wg_redirect_uri: 'http://<host>:<port>/auth/game'
  wg_uri: 'https://api.worldoftanks.<region>/wot/auth/login/?application_id=<app_id>?redirect_uri=<redirect_uri>'

  ds_auth_redirect_url: 'http://<host>:<port>/auth/discord'

game_api:
  reg_urls:
    ru:   'papi.tanksblitz.ru'
    eu:   'api.wotblitz.eu'
    na:   'api.wotblitz.com'
    asia: 'api.wotblitz.asia'

  urls:
    get_id: 
      "https://<reg_url>/wotb/account/list/\
      ?application_id=<app_id>\
      &search=<nickname>\
      &type=<search_type>"

    get_stats:
      "https://<reg_url>/wotb/account/info/\
      ?application_id=<app_id>\
      &account_id=<player_id>\
      &extra=statistics.rating\
      &fields=-statistics.clan"

    get_achievements:
      "https://<reg_url>/wotb/account/achievements/\
      ?application_id=<app_id>\
      &fields=-max_series\
      &account_id=<player_id>"

    get_clan_stats:
      "https://<reg_url>/wotb/clans/accountinfo/\
      ?application_id=<app_id>\
      &account_id=<player_id>\
      &extra=clan"

    get_tank_stats:
      "https://<reg_url>/wotb/tanks/stats/\
      ?application_id=<app_id>\
      &account_id=<player_id>"

ds_api:
  urls:
    get_user: 'https://discord.com/api/v9/users/@me'

report:
  suggestion_channel_id: 1209275221287379034
  bug_channel_id: 1209275221287379034

dump:
  export_to_id: 647499212073861151
  chunk_size: 24_117_248  #in bytes(now is 23 MB)
  directory: dump
