---
# This YAML file use placeholders:
# format: <key_name>
#
# Example:
#   srv_id: "server_id: <id>"
#
# This YAML file is loaded by the Python library dynamic-yaml, 
# which allows you to use variables in the file
#
# Example:
# server:
#   port: 8080
#
# message:
#   server_running: 'server started on port {server.port}'

bot_name:
  'Blitz Statistics'

server:
  host: '127.0.0.1'
  port: '8000'
  protocol: 'http'

session:
  ttl: 3_888_000 # in seconds - 45 days

autosession:
  ttl: 3_888_000 # in seconds - 45 days

account:
  inactive_ttl: 15_552_000 # in seconds (180 days)

default:
  prefix : '!'  # deprecated | unused
  lang: 'en'
  available_locales: ['ru', 'en', 'pl', 'ua', 'auto']
  available_regions: ['ru', 'eu', 'na', 'asia']
  locale_aliases: {ru: 'ru', en: 'en', pl: 'pl', uk: 'ua', en-GB: 'en', en-US: 'en'}

image:
  default_bg_path: 'res/image/default_image/default_bg.png'
  available_stats: [
    winrate, avg_damage, battles,
    accuracy, hits, frags,
    wins, losses, capture_points,
    damage_dealt, damage_received, shots,
    xp, survived_battles, dropped_capture_points,
    damage_ratio, destruction_ratio, frags_per_battle,
    avg_spotted, survival_ratio, empty
    ]
  available_rating_stats: [
    winrate, avg_damage, battles,
    accuracy, hits, frags,
    wins, losses, capture_points,
    damage_dealt, damage_received, shots,
    xp, survived_battles, dropped_capture_points,
    damage_ratio, destruction_ratio, frags_per_battle,
    avg_spotted, survival_ratio, rating, empty
    ]

themes:
  available: ['default', 'tiger_girl', 'alpine']

internal:
  ignore_tankopedia_failures: true

help_urls:
  ru: https://blitzhub.gitbook.io/blitz-statistics-bot/ru-docs
  en: https://blitzhub.gitbook.io/blitz-statistics-bot/en-docs
  ua: https://blitzhub.gitbook.io/blitz-statistics-bot/ua-docs
  pl: https://blitzhub.gitbook.io/blitz-statistics-bot/pl-docs

session_widget:
  url: '{server.protocol}://{server.host}:{server.port}/bot/ui/session_widget_app?p_id=<user_id>&lang=<lang>&slot_n=<slot>'

auth:
  wg_redirect_uri: '{server.protocol}://{server.host}:{server.port}/bot/auth/game?region=<region>&requested_by=<requested_by>&slot_n=<slot>'
  wg_uri: 'https://api.worldoftanks.<region>/wot/auth/login/?application_id=<app_id>&redirect_uri=<redirect_uri>&display=popup'

  ds_auth_redirect_url: '{server.protocol}://{server.host}:{server.port}/bot/auth/discord'
  ds_auth_primary_uri: 'https://discord.com/oauth2/authorize?client_id=<client_id>&response_type=code&redirect_uri=<redirect_uri>&scope=identify'

game_api:
  reg_urls:
    ru:   'papi.tanksblitz.ru'
    eu:   'api.wotblitz.eu'
    na:   'api.wotblitz.com'
    asia: 'api.wotblitz.asia'

  urls:
    get_id: >
      https://<reg_url>/wotb/account/list/
      ?application_id=<app_id>
      &search=<nickname>
      &type=<search_type>

    get_stats:
      "https://<reg_url>/wotb/account/info/\
      ?application_id=<app_id>\
      &account_id=<player_id>\
      &extra=statistics.rating\
      &fields=-statistics.clan"

    get_achievements:
      "https://<reg_url>/wotb/account/achievements/\
      ?application_id=<app_id>\
      &fields=-max_series\
      &account_id=<player_id>"

    get_clan_stats:
      "https://<reg_url>/wotb/clans/accountinfo/\
      ?application_id=<app_id>\
      &account_id=<player_id>\
      &extra=clan"

    get_tank_stats:
      "https://<reg_url>/wotb/tanks/stats/\
      ?application_id=<app_id>\
      &account_id=<player_id>"

ds_api:
  urls:
    get_user: 'https://discord.com/api/v9/users/@me'

report:
  suggestion_channel_id: 1214204057477054464
  bug_channel_id: 1214204057477054464

dump:
  export_to_id: 1243198882180235344
  chunk_size: 24_117_248  #in bytes(now is 23 MB)
  directory: dump

premium:
  passed_server: 
    id: 1004871731799933019 # Support server RU
    premium_roles: [
      1149629590235525140, #dev
      1149630277040226356, #admin
      1231328253898260570, #tester
      1149671086724755527, #beta_tester
      1202636715450175578, #boosty
      1174701169763946577  #server_booster
    ]
